name: Build FFmpeg Static

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main # Trigger on pushes to main branch

jobs:
  build:
    # Use an older Ubuntu version to get an older GLIBC for broader compatibility
    # Ubuntu 18.04 (Bionic Beaver) uses GLIBC 2.27 or 2.28
    runs-on: ubuntu-18.04 # IMPORTANT for GLIBC compatibility

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt update
          # Install build tools and essential dependencies
          sudo apt install -y build-essential nasm automake libtool git pkg-config zlib1g-dev libnuma-dev

          # Create build directories
          mkdir -p ~/ffmpeg_sources ~/ffmpeg_build ~/bin
          echo "HOME=$HOME" >> $GITHUB_ENV # Ensure HOME is set for subsequent steps
          echo "$HOME/bin" >> $GITHUB_PATH # Add local bin to PATH for subsequent steps

      - name: Compile x264
        run: |
          cd ~/ffmpeg_sources
          git clone --depth 1 https://code.videolan.org/videolan/x264.git
          cd x264
          ./configure --prefix="$HOME/ffmpeg_build" --enable-static --enable-pic --disable-opencl
          make -j$(nproc)
          make install

      - name: Compile FFmpeg
        run: |
          cd ~/ffmpeg_sources
          git clone --depth 1 https://github.com/FFmpeg/FFmpeg.git
          cd FFmpeg

          ./configure \
              --prefix="$HOME/ffmpeg_build" \
              --pkg-config-flags="--static" \
              --extra-cflags="-I$HOME/ffmpeg_build/include" \
              --extra-ldflags="-L$HOME/ffmpeg_build/lib" \
              --bindir="$HOME/bin" \
              --enable-gpl \
              --enable-libx264 \
              --enable-version3 \
              --disable-shared \
              --enable-static \
              --enable-zlib \
              --enable-filter=overlay \
              # Add other desired enabled libraries here, e.g.:
              # --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libwebp

          make -j$(nproc)
          make install

      - name: Verify FFmpeg build
        run: |
          ~/bin/ffmpeg -version
          ldd ~/bin/ffmpeg

      - name: Upload FFmpeg binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-static-linux-amd64
          path: ~/bin/ffmpeg
          retention-days: 7 # How long to keep the artifact

      # Optional: Make the binary executable on the runner before upload if not already
      - name: Make executable (redundant if make install handles this)
        run: chmod +x ~/bin/ffmpeg
        continue-on-error: true # Don't fail if already executable
