name: Build FFmpeg with libx264 (Linux amd64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y autoconf automake build-essential cmake git libtool pkg-config yasm nasm

      - name: Clone and Build x264
        run: |
          git clone --depth 1 https://code.videolan.org/videolan/x264.git
          cd x264
          ./configure --prefix=$HOME/ffmpeg_build --enable-static
          make -j$(nproc)
          make install

      - name: Clone FFmpeg
        run: |
          git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg

      - name: Build FFmpeg with libx264
        run: |
          cd ffmpeg
          PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure \
            --prefix="$HOME/ffmpeg_build" \
            --pkg-config-flags="--static" \
            --extra-cflags="-I$HOME/ffmpeg_build/include" \
            --extra-ldflags="-L$HOME/ffmpeg_build/lib" \
            --extra-libs="-lpthread -lm" \
            --enable-gpl \
            --enable-libx264 \
            --enable-static \
            --disable-shared \
            --disable-debug \
            --disable-doc
          make -j$(nproc)
          make install

      - name: Upload FFmpeg Binary
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-full-codec-linux
          path: /home/runner/ffmpeg_build/bin/ffmpeg

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "ffmpeg-full-codec-linux-reease"
          tag_name: "v1.0-${{ github.run_number }}"
          files: ${{ runner.home }}/ffmpeg_build/bin/ffmpeg